const SelectTypeEnum = Object.freeze({
  /**
   * CARRIER_STATUS
   */
  CARRIER_STATUS: "CARRIER_STATUS",
  ENABLED_TYPE: "ENABLED_TYPE",
  INBOUND_SOURCE: "INBOUND_SOURCE",
  INBOUND_STATUS: "INBOUND_STATUS",
  INVENTORY_STATUS: "INVENTORY_STATUS",
  INVENTORY_TYPE: "INVENTORY_TYPE",
  /**
   * 儲位狀態
   */
  LOCATION_STATUS: "LOCATION_STATUS",
  OPERATING_MODE: "OPERATING_MODE",
  OUTBOUND_STATUS: "OUTBOUND_STATUS",
  PROCESSING_STATUS: "PROCESSING_STATUS",
  SHIPPING_MODE: "SHIPPING_MODE",
  STOCK_MGMT_STATUS: "STOCK_MGMT_STATUS",
  USER_ROLE: "USER_ROLE",
  WORK_STATION: "WORK_STATION",
});

export default SelectTypeEnum;
